# Site and content
site_name: "Safespring documentation"
docs_dir: "content"

# Github integration
repo_name: "safespring/docs"
repo_url: "https://github.com/safespring/docs"
edit_uri: "edit/master/content/"

# Safespring theme
theme: "material"
extra_css:
  - "safespring.css"
extra:
  logo: "safespring.png"
  font:
    text: "Hind"
    code: "Ubuntu Mono"

# Pages layout
pages:
  - Overview: "index.md"
  - Backup: "backup.md"
  - Compute: "compute.md"
  - Storage: "storage.md"
  - Status information: "status.md"
  - Support: "support.md"
  - Contributing: "contribute.md"

