# Site and content
site_name: "Safespring documentation"
docs_dir: "content"

# Github integration
repo_name: "safespring/docs"
repo_url: "https://github.com/safespring/docs"
edit_uri: "edit/master/content/"

# Safespring theme
theme:
  name: "material"
  feature:
    tabs: false
  logo: "safespring.png"
  favicon: "favicon.ico"
extra_css:
  - "safespring.css"
extra:
  font:
    text: "Hind"
    code: "Ubuntu Mono"

# https://squidfunk.github.io/mkdocs-material/getting-started/#extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Pages layout
pages:
  - Overview: "index.md"
  - Backup:
    - Status: "backup/status.md"
    - Getting started: "backup/getting-started.md"
    - Introduction: "backup/introduction.md"
    - Installation:
      - Overview: "backup/install/overview.md"
      - Apple OSX: "backup/install/apple-osx.md"
      - Debian/Ubuntu: "backup/install/debian-ubuntu.md"
      - FreeBSD/other: "backup/install/freebsd-other.md"
      - RHEL: "backup/install/rhel.md"
      - Windows: "backup/install/windows.md"
      - TDP for MSSQL: "backup/install/tdp-for-mssql.md"
    - Performance: "backup/performance.md"
    - Howtos:
      - Alternate restore: "backup/howto/restore-alternate.md"
      - vSphere: "backup/howto/vsphere.md"
      - Encryption: "backup/howto/encrypted.md"
      - Includes & Excludes: "backup/howto/includeexclude.md"
      - Performance tuning: "backup/howto/performance-tuning.md"
      - Bare metal recovery: "backup/howto/bare-metal-tbmr.md"
      - Virtual environments single file restore: "backup/howto/virtual-enviroments-single-file-restore.md"
      - Handling changing files: "backup/howto/changing-files.md"
    - API: "backup/api.md"
    - FAQ: "backup/faq.md"
  - Compute:
    - Getting started: "compute/getting-started.md"
    - API access: "compute/api.md"
    - Image service: "compute/image.md"
    - Volume service: "compute/volume.md"
    - Network service: "compute/network.md"
    - Using Keypairs: "compute/keypairs.md"
    - Enabling IPv6: "compute/ipv6-howto.md"
    - Connecting to Safespring: "compute/connecting.md"
    - Windows images: "compute/windows.md"
    - VMware import: "compute/vmware-import.md"
    - Migrate instance to another project: "compute/migrate-between-projects.md"
  - Storage:
    - General S3 Info: "storage/generalinfo.md"
    - Example s3cmd config: "storage/s3cmd.md"
    - Example s3fs config: "storage/s3fs.md"
    - Example CloudBerry config: "storage/cloudberry.md"
    - Example CyberDuck config: "storage/cyberduck.md"
    - Example Duck CLI config: "storage/duck-cli.md"
    - Tips and Tricks: "storage/tips-n-tricks.md"
  - Service status: "status.md"
    #  - Domain changes: "domain-changes.md"
  - Support: "support.md"
  - Contributing: "contribute.md"

