site_name: "Safespring documentation"
docs_dir: "content"

repo_name: "safespring/docs"
repo_url: "https://github.com/safespring/docs"

theme: "material"

extra:
  logo: "safespring.png"
  font:
    text: "Hind"
    code: "Ubuntu Mono"

extra_css:
  - "safespring.css"

pages:
  - Overview: "index.md"
  - Backup: "backup/backup.md"
  - Compute: "compute/compute.md"
  - Storage: "storage/storage.md"
  - Status information: "status.md"
  - Support: "support.md"
  - Contributing: "contribute.md"

