# Site and content
site_name: "Safespring documentation"
docs_dir: "content"

# Github integration
repo_name: "safespring/docs"
repo_url: "https://github.com/safespring/docs"
edit_uri: "edit/master/content/"

# Safespring theme
theme: "material"
extra_css:
  - "safespring.css"
extra:
  logo: "safespring.png"
  font:
    text: "Hind"
    code: "Ubuntu Mono"

# Pages layout
pages:
  - Overview: "index.md"
  - Backup: "backup.md"
  - Compute:
    - Getting started: "compute.md"
    - Image service: "compute/image.md"
    - Network service: "compute/network.md"
    - Using Keypairs: "compute/keypairs.md"
    - Enabling IPv6: "compute/ipv6-howto.md"
  - Storage: "storage.md"
  - Service status: "status.md"
  - Support: "support.md"
  - Contributing: "contribute.md"

