site_name: "docs.safespring.com"
docs_dir: "content"

repo_name: "safespring/docs"
repo_url: "https://github.com/safespring/docs"

theme: "material"

extra:
  logo: "assets/images/logo.png"
  font:
    text: "Hind"
    code: "Ubuntu Mono"

extra_css:
  - "assets/stylesheets/palette.css"

pages:
  - Overview: "index.md"
  - Safespring Backup: "backup.md"
  - Safespring Compute: "compute.md"
  - Safespring Storage: "storage.md"

